# Generated by Django 4.1.7 on 2023-03-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=8, max_digits=38)),
                ('change_24h', models.DecimalField(decimal_places=8, max_digits=38)),
                ('volume_24h', models.DecimalField(decimal_places=8, max_digits=38)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto', to='api.cryptocurrency', verbose_name='криптовалюта')),
            ],
            options={
                'verbose_name': 'избранная криптовалюта',
                'verbose_name_plural': 'избранные криптовалюты',
            },
        ),
    ]
